'use client';
import {useEffect,useState,useRef} from 'react';
import {authFetch} from '../lib/supabase/client';
import {useFamilyAccount} from '../lib/family/account-context';
import HouseholdSettings from '../components/household-settings';
import ShoppingPresets from '../components/shopping-presets';
import FamilyHome from '../components/family-home';
import FamilyCalendar from '../components/family-calendar';
import FamilyProfileEditor from '../components/family-profile';
import {pragueToday,dateLabel,type FamilyEvent,type FamilyProfile} from '../lib/family/calendar';
import { applyShoppingPreset, type ShoppingPreset } from '../lib/family/presets';
import {Home,ShoppingBasket,CalendarDays,ChefHat,Plus,Check,Trash2,ArrowRight,Sparkles,Leaf,Clock,Users,ChevronLeft,ChevronRight,House,Plane,Heart} from 'lucide-react';
type Item={id:string;name:string;qty:string;cat:string;done:boolean};
type State={items:Item[];plan:{date:string;recipe:number;servings:number}[];presets:ShoppingPreset[];events:FamilyEvent[]};
const cats=['Ovoce a zelenina','Pečivo','Maso a ryby','Mléčné a vejce','Trvanlivé','Drogerie','Ostatní'];
const recipes=[
{name:'Kuře na paprice',emoji:'🍲',tag:'Česká klasika',time:45,ingredients:[['Kuřecí maso',400,'g',2],['Cibule',1,'ks',0],['Smetana',200,'ml',3],['Rýže',160,'g',4]],steps:'Cibuli orestujte, přidejte kuřecí maso a sladkou papriku. Podlijte, duste do úplného propečení masa, přidejte smetanu a podávejte s uvařenou rýží.'},
{name:'Těstoviny s rajčaty',emoji:'🍝',tag:'Bez masa',time:20,ingredients:[['Těstoviny',200,'g',4],['Rajčata',300,'g',0],['Česnek',2,'stroužky',0],['Parmazán',40,'g',3]],steps:'Uvařte těstoviny. Na oleji krátce orestujte česnek, přidejte rajčata a povařte. Spojte s těstovinami a posypte sýrem.'},
{name:'Kuřecí tortilly',emoji:'🌮',tag:'Rychlá večeře',time:25,ingredients:[['Tortilly',4,'ks',4],['Kuřecí maso',300,'g',2],['Paprika',1,'ks',0],['Bílý jogurt',150,'g',3]],steps:'Nakrájené kuře orestujte a důkladně propečte, přidejte papriku. Tortilly prohřejte, naplňte a doplňte jogurtem.'},
{name:'Pečené brambory s tvarohem',emoji:'🥔',tag:'Bez masa',time:40,ingredients:[['Brambory',500,'g',0],['Tvaroh',250,'g',3],['Pažitka',1,'svazek',0]],steps:'Brambory nakrájejte, osolte, pokapejte olejem a pečte při 200 °C doměkka. Tvaroh promíchejte s pažitkou a podávejte.'},
{name:'Losos s kuskusem',emoji:'🐟',tag:'Za půl hodiny',time:25,ingredients:[['Losos',300,'g',2],['Kuskus',160,'g',4],['Citron',1,'ks',0],['Cuketa',1,'ks',0]],steps:'Kuskus zalijte horkou vodou podle obalu. Lososa a cuketu opečte do hotova a podávejte s citronem.'},
{name:'Čočková polévka',emoji:'🥣',tag:'Na dva dny',time:35,ingredients:[['Červená čočka',180,'g',4],['Mrkev',2,'ks',0],['Cibule',1,'ks',0],['Rajčata v plechovce',400,'g',4]],steps:'Orestujte cibuli a mrkev, přidejte propláchnutou čočku, rajčata a vodu. Vařte asi 20 minut do změknutí. Dochuťte solí a kmínem.'}
];
function dateStr(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
export default function Hub({initialInvite=''}:{initialInvite?:string}){
 const account=useFamilyAccount();const revision=useRef(0);const saving=useRef(false);const [householdOpen,setHouseholdOpen]=useState(Boolean(initialInvite));
 const [tab,setTab]=useState('Přehled'),[state,setState]=useState<State>({items:[],plan:[],presets:[],events:[]}),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState('Načítání…');
 const [today,setToday]=useState(pragueToday()),[profile,setProfile]=useState<FamilyProfile>({name:'Můj profil',color:'#416443'}),[profileLoaded,setProfileLoaded]=useState(false),[profileOpen,setProfileOpen]=useState(false);
 useEffect(()=>{authFetch('/api/profile').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{setProfile(data as FamilyProfile);setProfileLoaded(true)}).catch(()=>setStatus('Profil se nepodařilo načíst. Obnovte stránku.'));const timer=setInterval(()=>setToday(pragueToday()),60000);return()=>clearInterval(timer)},[]);
 async function saveProfile(next:FamilyProfile){try{const r=await authFetch('/api/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)});if(!r.ok)throw Error();setProfile(await r.json() as FamilyProfile);await account.refreshHousehold();return true}catch{return false}}
 const [name,setName]=useState(''),[qty,setQty]=useState('1 ks'),[cat,setCat]=useState(cats[0]),[week,setWeek]=useState(0),[detail,setDetail]=useState<number|null>(null),[choice,setChoice]=useState<string|null>(null),[portions,setPortions]=useState(2),[style,setStyle]=useState('Pestrý týden'),[proposal,setProposal]=useState<number[]|null>(null);
 const monday=new Date();monday.setDate(monday.getDate()-(monday.getDay()+6)%7+week*7);const days=Array.from({length:7},(_,i)=>{const d=new Date(monday);d.setDate(d.getDate()+i);return {key:dateStr(d),label:d.toLocaleDateString('cs',{weekday:'long'}),short:d.toLocaleDateString('cs',{day:'numeric',month:'numeric'})}});
 async function loadState(){const response=await authFetch('/api/hub');if(!response.ok)throw Error();const result=await response.json() as {data:State;revision:number};if(!saving.current&&result.revision>=revision.current){setState({...result.data,presets:result.data.presets??[],events:result.data.events??[]});revision.current=result.revision;setReady(true);setStatus('Synchronizováno')}}
 useEffect(()=>{let active=true;loadState().catch(()=>{if(active)setStatus('Data se nepodařilo načíst. Obnov stránku.')});const interval=setInterval(()=>{if(!saving.current)loadState().catch(()=>{if(active)setStatus('Synchronizace selhala. Zkus obnovit stránku.')})},10000);return()=>{active=false;clearInterval(interval)}},[]);
 async function save(next:State){if(!ready||saving.current)return false;saving.current=true;setBusy(true);setStatus('Ukládání…');try{const r=await authFetch('/api/hub',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:next,revision:revision.current})});if(r.status===409){saving.current=false;await loadState();setStatus('Jiné zařízení změnilo seznam. Zopakuj akci.');return false}if(!r.ok)throw Error();const result=await r.json() as {revision:number};revision.current=result.revision;setState(next);setStatus('Synchronizováno');return true;}catch{setStatus('Uložení selhalo. Zkus akci znovu.');return false;}finally{saving.current=false;setBusy(false)}}
 function add(){if(!name.trim())return;save({...state,items:[...state.items,{id:crypto.randomUUID(),name:name.trim(),qty,cat,done:false}]});setName('')}
 function ingredients(entries:State['plan']){const items=[...state.items];for(const e of entries){for(const ing of recipes[e.recipe].ingredients){const [n,q,u,c]=ing;const amount=Number(q)*e.servings/2;const existing=items.find(x=>!x.done&&x.name===n&&x.cat===cats[Number(c)]&&x.qty.endsWith(' '+u));if(existing&&Number.isFinite(parseFloat(existing.qty))) {const index=items.indexOf(existing);items[index]={...existing,qty:`${parseFloat(existing.qty)+amount} ${u}`}}else items.push({id:crypto.randomUUID(),name:String(n),qty:`${amount} ${u}`,cat:cats[Number(c)],done:false})}}save({...state,items});setTab('Nákupy')}
 const remaining=state.items.filter(x=>!x.done).length;const thisPlan=state.plan.filter(p=>days.some(d=>d.key===p.date));
 return <div className="app"><aside><a className="brand" href="/"><span className="brandicon"><House size={23}/></span> family<span>hub</span></a><p className="caption">NÁŠ SPOLEČNÝ PROSTOR</p><nav>{[['Přehled',Home],['Rodinný kalendář',CalendarDays],['Nákupy',ShoppingBasket],['Jídelníček',ChefHat],['Cesty',Plane],['Domov',House]].map(([t,I])=>{const Icon=I as typeof Home;return <button key={String(t)} className={tab===t?'active':''} onClick={()=>setTab(String(t))}><Icon size={20}/><span className="navlabel">{t==='Přehled'?'Domů':t==='Nákupy'?'Nákupy a jídlo':String(t)}</span><span className="mobilenavlabel">{t==='Přehled'?'Domů':t==='Rodinný kalendář'?'Kalendář':t==='Jídelníček'?'Menu':String(t)}</span>{t==='Nákupy'&&remaining>0&&<b>{remaining}</b>}</button>})}</nav><button className="account accountbutton" disabled={!profileLoaded} onClick={()=>setProfileOpen(true)} aria-label="Upravit můj profil"><div className="avatar" style={{background:profile.color,color:'white'}}>{profile.name.slice(0,1).toUpperCase()}</div><div><strong>{profile.name}</strong><small>Můj profil · nastavení</small></div></button></aside><main><header><button className="householdtoggle" onClick={()=>setHouseholdOpen(true)}>{account.household.name}</button><button className="profilemobile" disabled={!profileLoaded} onClick={()=>setProfileOpen(true)} aria-label="Upravit můj profil"><span style={{background:profile.color}}>{profile.name.slice(0,1).toUpperCase()}</span> Můj profil</button><span className="sync">{status}</span></header><div className="content"><div className="title"><div><p className="eyebrow">MÉNĚ PLÁNOVÁNÍ. VÍCE ČASU SPOLU.</p><h1>{tab==='Přehled'?'Ahoj rodinko!':tab==='Rodinný kalendář'?'Rodinný kalendář':tab==='Nákupy'?'Nákupy a jídlo':tab==='Jídelníček'?'Jídelníček':tab==='Cesty'?'Cesty':tab==='Domov'?'Domov':'Naše kuchařka'}</h1><p>{tab==='Přehled'?'Co vás dnes a v dalších dnech čeká?':tab==='Rodinný kalendář'?'Všechny důležité termíny na jednom místě.':tab==='Nákupy'?'Přidej položky, v obchodě je jednoduše odškrtni.':tab==='Jídelníček'?'Naplánuj večeře a suroviny pošli rovnou do nákupu.':tab==='Cesty'||tab==='Domov'?'Tuto část budeme rozvíjet v další fázi.':'Jednoduchá jídla pro běžné rodinné dny.'}</p></div><span className="date">{dateLabel(today)}</span></div>
{tab==='Přehled'&&<FamilyHome events={state.events} profile={profile} today={today} disabled={!ready||busy} onSave={events=>save({...state,events})} navigate={setTab}/>}
{tab==='Rodinný kalendář'&&<FamilyCalendar events={state.events} profile={profile} today={today} disabled={!ready||busy} onSave={events=>save({...state,events})}/>}
{(tab==='Cesty'||tab==='Domov')&&<section className="card empty"><h2>Připravujeme</h2><p>{tab==='Cesty'?'Tady budou vaše výlety, itineráře a seznamy na balení.':'Tady budou informace, dokumenty a úkoly kolem domácnosti.'}</p></section>}
{(tab==='Nákupy'||tab==='Jídelníček'||tab==='Recepty')&&<div className="foodnav"><button className={tab==='Nákupy'?'active':''} onClick={()=>setTab('Nákupy')}>Nákupní seznamy</button><button className={tab==='Jídelníček'?'active':''} onClick={()=>setTab('Jídelníček')}>Jídelníček</button><button className={tab==='Recepty'?'active':''} onClick={()=>setTab('Recepty')}>Recepty</button></div>}
{(tab==='Nákupy'||tab==='Jídelníček')&&<section className="assistant"><div className="spark"><Sparkles/></div><div><p className="eyebrow">NÁKUPNÍ ASISTENT</p><h2>Večeře vymyšlené. Nákup připravený.</h2><p>Vyber styl týdne a počet porcí. Navrhnu pět večeří z naší kuchařky.</p><div className="controls"><select aria-label="Styl jídelníčku" value={style} onChange={e=>setStyle(e.target.value)}>{['Pestrý týden','Rychlé večeře','Bez masa'].map(s=><option key={s}>{s}</option>)}</select><select aria-label="Počet porcí" value={portions} onChange={e=>setPortions(+e.target.value)}>{[1,2,3,4,6].map(n=><option key={n} value={n}>{n} porce</option>)}</select><button className="primary" onClick={()=>setProposal(style==='Bez masa'?[1,3,5,1,3]:style==='Rychlé večeře'?[1,2,4,1,2]:[0,1,2,3,5])}>Navrhnout jídelníček <ArrowRight size={16}/></button></div><small>Návrhy z připravených receptů · bez konverzační AI</small></div><div className="illustration">🍋<span>🌿</span></div></section>}
{proposal&&<section className="card proposal"><h2>Návrh na pondělí až pátek</h2><p>Pro týden {days[0].short} – {days[6].short}, {portions} porce denně.</p>{proposal.map((r,i)=><div className="proposalrow" key={i}><span>{days[i].label}</span><strong>{recipes[r].emoji} {recipes[r].name}</strong></div>)}<button disabled={!ready||busy} className="primary" onClick={()=>{save({...state,plan:[...state.plan.filter(p=>!days.slice(0,5).some(d=>d.key===p.date)),...proposal.map((r,i)=>({date:days[i].key,recipe:r,servings:portions}))]});setProposal(null)}}>Potvrdit jídelníček</button> <button className="plain" onClick={()=>setProposal(null)}>Zrušit</button></section>}
{tab==='Jídelníček'&&<section className="card"><div className="sectionhead"><h2>Tento týden na talíři</h2><div className="controls"><button aria-label="Předchozí týden" onClick={()=>setWeek(week-1)}><ChevronLeft size={18}/></button><span>{days[0].short} – {days[6].short}</span><button aria-label="Další týden" onClick={()=>setWeek(week+1)}><ChevronRight size={18}/></button></div></div><div className="week">{days.map(d=>{const p=state.plan.find(x=>x.date===d.key);return <div className="day" key={d.key}><p>{d.label}<small>{d.short}</small></p>{p?<><div className="foodemoji">{recipes[p.recipe].emoji}</div><button className="recipename" onClick={()=>setDetail(p.recipe)}>{recipes[p.recipe].name}</button><small>{p.servings} porce</small><button disabled={busy} className="plain" onClick={()=>setChoice(d.key)}>Změnit</button><button disabled={busy} className="plain" onClick={()=>save({...state,plan:state.plan.filter(x=>x.date!==d.key)})}>Odebrat</button></>:<button className="emptyday" onClick={()=>setChoice(d.key)}><Plus size={20}/>Vybrat jídlo</button>}</div>})}</div><div className="sectionfoot"><span>Suroviny sečteme podle počtu porcí.</span><button className="primary" disabled={!thisPlan.length||busy||!ready} onClick={()=>ingredients(thisPlan)}><ShoppingBasket size={17}/> Přidat suroviny do nákupu</button></div><small>Každé kliknutí přidá další množství. Olej, sůl a běžné koření zkontroluj doma.</small></section>}
{tab==='Nákupy'&&<ShoppingPresets presets={state.presets} items={state.items} disabled={!ready||busy} onSave={presets=>save({...state,presets})} onApply={async preset=>{const result=applyShoppingPreset(state.items,preset,()=>crypto.randomUUID());const saved=await save({...state,items:result.items});return saved?{added:result.added,skipped:result.skipped}:null}}/>}
{tab==='Nákupy'&&<section className="card"><form className="addform" onSubmit={e=>{e.preventDefault();add()}}><input aria-label="Název položky" placeholder="Co nám doma chybí?" value={name} onChange={e=>setName(e.target.value)} required maxLength={100}/><input aria-label="Množství" value={qty} onChange={e=>setQty(e.target.value)} maxLength={40}/><select aria-label="Kategorie" value={cat} onChange={e=>setCat(e.target.value)}>{cats.map(c=><option key={c}>{c}</option>)}</select><button className="primary" disabled={!ready||busy}><Plus size={18}/> Přidat</button></form><div className="sectionhead"><span>{remaining} zbývá · {state.items.filter(x=>x.done).length} koupeno</span><button className="plain" disabled={busy||!ready} onClick={()=>save({...state,items:state.items.filter(x=>!x.done)})}>Odstranit koupené</button></div>{state.items.length===0&&<div className="empty"><ShoppingBasket size={40}/><h2>Začínáme s prázdným košíkem</h2><p>Přidej první položku nebo suroviny z jídelníčku.</p></div>}{cats.map(c=>{const rows=state.items.filter(x=>x.cat===c);return rows.length>0&&<div className="category" key={c}><h3>{c}</h3>{rows.map(x=><div className={'item '+(x.done?'done':'')} key={x.id}><button aria-label={`Označit ${x.name}`} disabled={busy} className="checkbox" onClick={()=>save({...state,items:state.items.map(i=>i.id===x.id?{...i,done:!i.done}:i)})}>{x.done&&<Check size={16}/>}</button><strong>{x.name}</strong><span>{x.qty}</span><button aria-label={`Smazat ${x.name}`} className="plain" disabled={busy} onClick={()=>save({...state,items:state.items.filter(i=>i.id!==x.id)})}><Trash2 size={16}/></button></div>)}</div>})}</section>}
{tab==='Recepty'&&<div className="recipegrid">{recipes.map((r,i)=><button className="card recipe" key={r.name} onClick={()=>setDetail(i)}><div className={'recipeart art'+i}>{r.emoji}</div><span className="tag">{r.tag}</span><h2>{r.name}</h2><p><Clock size={15}/>{r.time} min <Users size={15}/> 2 porce</p><span className="link">Zobrazit recept →</span></button>)}</div>}
<footer>Family Hub · Malé plány pro velké společné chvíle.<br/>Sdíleno s členy vaší domácnosti. Každý má svůj účet.</footer></div></main>
{householdOpen&&<HouseholdSettings initialInvite={initialInvite} onClose={()=>setHouseholdOpen(false)}/>}
{profileOpen&&<FamilyProfileEditor profile={profile} loaded={profileLoaded} onSave={saveProfile} onClose={()=>setProfileOpen(false)}/>}
{(detail!==null||choice)&&<div className="overlay" onClick={()=>{setDetail(null);setChoice(null)}}><div role="dialog" aria-modal="true" aria-label={choice?'Vybrat jídlo':'Recept'} className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>{setDetail(null);setChoice(null)}} aria-label="Zavřít">×</button>{choice?<><h2>Vyber jídlo</h2><label>Počet porcí <select value={portions} onChange={e=>setPortions(+e.target.value)}>{[1,2,3,4,6].map(n=><option key={n}>{n}</option>)}</select></label>{recipes.map((r,i)=><button disabled={!ready||busy} className="choose" key={r.name} onClick={()=>{save({...state,plan:[...state.plan.filter(p=>p.date!==choice),{date:choice,recipe:i,servings:portions}]});setChoice(null)}}>{r.emoji} {r.name}<Plus size={18}/></button>)}</>:detail!==null&&<><div className="foodemoji">{recipes[detail].emoji}</div><h2>{recipes[detail].name}</h2><p>{recipes[detail].time} minut · suroviny na 2 porce</p><h3>Suroviny</h3>{recipes[detail].ingredients.map(([n,q,u])=><p className="ingredient" key={String(n)}><span>{n}</span><strong>{q} {u}</strong></p>)}<small>Navíc olej, sůl a koření podle chuti.</small><h3>Postup</h3><p>{recipes[detail].steps}</p><button disabled={!ready||busy} className="primary" onClick={()=>{ingredients([{date:'',recipe:detail,servings:2}]);setDetail(null)}}>Přidat suroviny pro 2 porce</button></>}</div></div>}</div>
}
