'use client';
import {useState} from 'react';
import {CalendarDays,Link,RefreshCw,Unplug,X} from 'lucide-react';
import {useFamilyAccount} from '../lib/family/account-context';
import type {Provider} from '../lib/calendar/feed';
import type {CalendarModel} from '../lib/calendar/use-calendars';
export default function CalendarConnections({model}:{model:CalendarModel}){
 const account=useFamilyAccount();const [provider,setProvider]=useState<Provider|null>(null),[label,setLabel]=useState(''),[url,setUrl]=useState(''),[share,setShare]=useState(false),[publicLink,setPublicLink]=useState(false),[disconnect,setDisconnect]=useState<string|null>(null);
 function open(p:Provider){setProvider(p);setLabel(p==='google'?'Můj Google kalendář':'Můj iCloud kalendář');setUrl('');setShare(false);setPublicLink(false)}
 async function connect(){if(!provider||model.busy)return;if(await model.mutate({action:'connect',provider,label,url,shareWithFamily:share,publicLinkAcknowledged:publicLink})){setProvider(null);setUrl('')}}
 return <div className="calconnections"><div className="sectionhead"><div><h3><Link size={16}/> Propojené kalendáře</h3><p>Události z vašich kalendářů na jednom místě.</p></div></div><div className="calendarproviderbuttons"><button disabled={model.busy||!model.loaded} onClick={()=>open('google')}><CalendarDays size={17}/> Připojit Google kalendář</button><button disabled={model.busy||!model.loaded} onClick={()=>open('apple')}><CalendarDays size={17}/> Připojit Apple / iCloud</button></div>{!model.loaded&&<p>Načítání propojení…</p>}{model.loaded&&model.data.sources.length===0&&<p>Zatím nemáte připojený žádný externí kalendář.</p>}{model.data.sources.map(source=>{const member=account.household.members.find(m=>m.user_id===source.ownerId);const own=source.ownerId===account.userId;return <div className="calendarsource" key={source.id}><i style={{background:member?.color}}/><div><strong>{source.label}</strong><small>{member?.name||'Člen rodiny'} · {source.provider==='google'?'Google':'iCloud'} · {source.count} událostí</small><small>Načteno {new Date(source.syncedAt).toLocaleString('cs-CZ',{timeZone:'Europe/Prague'})}</small></div>{own&&<><button aria-label={`Obnovit ${source.label}`} disabled={model.busy} onClick={()=>void model.mutate({action:'refresh',id:source.id})}><RefreshCw size={16}/></button><button aria-label={`Odpojit ${source.label}`} disabled={model.busy} onClick={()=>setDisconnect(source.id)}><Unplug size={16}/></button></>}</div>})}<p role="alert" className="preseterror">{model.error}</p><small>Načítáme posledních 30 dní a příští rok. Jen čtení · změny prováděj v původním kalendáři. Tvoje připojení obnovujeme každých 5 minut, když máš aplikaci otevřenou. Poskytovatel může změny zpřístupnit se zpožděním. Rodina vidí poslední načtené události.</small>
 {provider&&<div className="overlay"><div className="modal calendarconnectmodal" role="dialog" aria-modal="true" aria-label="Připojit kalendář"><button className="close" disabled={model.busy} aria-label="Zavřít" onClick={()=>{setProvider(null);setUrl('')}}><X size={22}/></button><h2>{provider==='google'?'Připojit Google kalendář':'Připojit Apple / iCloud'}</h2>{provider==='google'?<div className="calendarhelp"><p>Na počítači otevři Google Kalendář → Nastavení → vyber svůj kalendář → Integrovat kalendář → Tajná adresa ve formátu iCal. Zkopíruj odkaz sem.</p><p>Kalendář nemusíš zveřejňovat. Tajný odkaz umožňuje čtení kalendáře; v aplikaci ho ostatním členům nezobrazujeme.</p><a href="https://support.google.com/calendar/answer/37648?hl=cs" target="_blank" rel="noreferrer">Návod Google</a></div>:<div className="calendarhelp"><p>Na iPhonu: Kalendář → Kalendáře → ⓘ vedle iCloud kalendáře → Veřejný kalendář → Sdílet odkaz. Na iCloud.com lze odkaz zkopírovat v nabídce sdílení kalendáře.</p><p><strong>Veřejný odkaz umožní čtení komukoli, kdo ho získá.</strong> Zapni ho jen u kalendáře, pro který s tím souhlasíš. Kalendáře uložené pouze v telefonu takto připojit nelze.</p><a href="https://support.apple.com/guide/iphone/share-icloud-calendars-iph7613c4fb/ios" target="_blank" rel="noreferrer">Návod Apple</a></div>}<form className="eventform" onSubmit={e=>{e.preventDefault();void connect()}}><fieldset disabled={model.busy}><label>Název kalendáře<input autoFocus required maxLength={60} value={label} onChange={e=>setLabel(e.target.value)}/></label><label>Odkaz pro odběr kalendáře<input type="text" required maxLength={2000} value={url} autoComplete="off" spellCheck={false} placeholder={provider==='google'?'https://calendar.google.com/calendar/ical/…':'webcal://p…-calendars.icloud.com/published/2/…'} onChange={e=>setUrl(e.target.value)}/></label><label className="calendarconsent"><input type="checkbox" required checked={share} onChange={e=>setShare(e.target.checked)}/><span>Chci zobrazovat názvy, časy a poznámky událostí z tohoto kalendáře všem členům domácnosti „{account.household.name}“.</span></label>{provider==='apple'&&<label className="calendarconsent"><input type="checkbox" required checked={publicLink} onChange={e=>setPublicLink(e.target.checked)}/><span>Rozumím, že sdílení iCloud používá veřejný odkaz a jeho držitel může kalendář číst.</span></label>}<p className="preseterror" role="alert">{model.error}</p><div className="controls"><button type="button" onClick={()=>{setProvider(null);setUrl('')}}>Zrušit</button><button className="primary" disabled={model.busy||!share||(provider==='apple'&&!publicLink)}>{model.busy?'Načítání událostí…':'Připojit a zobrazit události'}</button></div></fieldset></form></div></div>}
 {disconnect&&<div className="overlay"><div className="modal" role="dialog" aria-modal="true" aria-label="Odpojit kalendář"><h2>Odpojit kalendář?</h2><p>Jeho načtené události zmizí z Family Hubu pro celou domácnost. Původní kalendář se nezmění. Odkaz můžeš u poskytovatele zneplatnit samostatně.</p><p role="alert" className="preseterror">{model.error}</p><div className="controls"><button disabled={model.busy} onClick={()=>setDisconnect(null)}>Zrušit</button><button className="primary" disabled={model.busy} onClick={async()=>{if(await model.mutate({action:'disconnect',id:disconnect}))setDisconnect(null)}}>Odpojit</button></div></div></div>}
 </div>
}
