'use client';
import {useState,useEffect} from 'react';
import {X,Copy,Users,LogOut} from 'lucide-react';
import {useFamilyAccount} from '../lib/family/account-context';
import {authFetch} from '../lib/supabase/client';
export default function HouseholdSettings({initialInvite,onClose}:{initialInvite:string;onClose:()=>void}){
 const account=useFamilyAccount();const [invite,setInvite]=useState(initialInvite),[working,setWorking]=useState(false),[message,setMessage]=useState(''),[importable,setImportable]=useState(false);
 useEffect(()=>{authFetch('/api/legacy-import').then(r=>r.json()).then(data=>setImportable(Boolean((data as {available?:boolean}).available))).catch(()=>{})},[]);
 async function importLegacy(){setWorking(true);try{const r=await authFetch('/api/legacy-import',{method:'POST'});const result=await r.json() as {error?:string};if(!r.ok)throw Error(result.error);setImportable(false);setMessage('Původní data byla přenesená. Obnov stránku, aby se načetla.')}catch(e){setMessage((e as Error).message)}finally{setWorking(false)}}
 async function newInvite(){setWorking(true);try{const r=await authFetch('/api/household',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'invite'})});const data=await r.json() as {invite:string;error?:string};if(!r.ok)throw Error(data.error);setInvite(data.invite);setMessage('Nová pozvánka je připravená. Starý kód už neplatí.')}catch(e){setMessage((e as Error).message)}finally{setWorking(false)}}
 async function copy(){try{await navigator.clipboard.writeText(invite);setMessage('Kód je zkopírovaný.')}catch{setMessage('Kód vyber a zkopíruj ručně.')}}
 return <div className="overlay"><div className="modal" role="dialog" aria-modal="true" aria-label="Domácnost"><button className="close" disabled={working} onClick={onClose} aria-label="Zavřít"><X size={22}/></button><Users size={28}/><h2>{account.household.name}</h2><p>Členové sdílejí nákupy, presety, jídelníček a kalendář.</p><div className="householdmembers">{account.household.members.map(member=><div key={member.user_id}><i style={{background:member.color}}/><strong>{member.name}</strong><span>{member.user_id===account.household.owner_id?'Správce':member.user_id===account.userId?'Ty':'Člen'}</span></div>)}</div>{account.household.owner_id===account.userId&&<><h3>Pozvat člena</h3><p className="calcaption">Člen si vytvoří svůj účet a zadá tento kód při připojení k domácnosti. Pozvánka platí 7 dní, domácnost může mít až 5 členů.</p>{invite&&<div className="invitecode"><input aria-label="Kód pozvánky" readOnly value={invite} onFocus={event=>event.target.select()}/><button aria-label="Zkopírovat pozvánku" onClick={copy}><Copy size={18}/></button></div>}<button disabled={working} onClick={newInvite}>{invite?'Vytvořit nový kód':'Vytvořit pozvánku'}</button></>}<p role="status" className="authnotice">{message}</p>{importable&&<section className="legacyimport"><h3>Předchozí verze aplikace</h3><p className="calcaption">Původní nákupy, presety a kalendář můžeme přenést do prázdné domácnosti. Původní data zůstanou zachovaná.</p><button disabled={working} onClick={importLegacy}>Přenést původní data</button></section>}<div className="settingsaccount"><small>{account.email}</small><button className="plain" onClick={account.signOut}><LogOut size={16}/> Odhlásit se</button></div></div></div>
}
